image: node:20

pipelines:
  default:
    - step:
        name: Run ESLint
        caches:
          - node
        script:
          - yarn install --ignore-engines
          - yarn lint

    - step:
        name: Run Prettier Check
        caches:
          - node
        script:
          - yarn install --ignore-engines
          - yarn prettier

    - step:
        name: Run Tests
        caches:
          - node
        services:
          - postgres
        script:
          - echo "APP_ENVIRONMENT=local" > .env
          - echo "DB_PASSWORD=postgres" >> .env
          - echo "DB_USERNAME=postgres" >> .env
          - echo "FS_DRIVER=s3" >> .env
          - yarn install
          - yarn add sharp --ignore-engines
          - yarn build
          - yarn test

  branches:
    develop:
      - step:
          name: Increment Package Version
          image: node:20
          caches:
            - node
          script:
            - git config --global user.email "suren@fifth-llc.com"
            - git config --global user.name "SurenAvagyanG"
            - git remote set-url origin https://SurenAvagyanG:${EXPIA_PIPELINE_TOKEN}@bitbucket.org/fifthllc/file_storage.git
            - yarn install
            - yarn add sharp --ignore-engines
            - yarn version --patch --no-git-tag-version
            - git add package.json
            - git commit -m "Incremented package version"
            - git push

  pull-requests:
    '**':
      - step:
          name: Check PR
          caches:
            - node
          script:
            - yarn install --ignore-engines
            - yarn lint
            - yarn prettier
            - yarn test

    develop:
      - step:
          name: Increment Package Version
          image: node:20
          caches:
            - node
          script:
            - git config --global user.email "suren@fifth-llc.com"
            - git config --global user.name "SurenAvagyanG"
            - git remote set-url origin https://SurenAvagyanG:${EXPIA_PIPELINE_TOKEN}@bitbucket.org/fifthllc/file_storage.git
            - yarn instal
            - yarn add sharp --ignore-engines
