version: 0.2

phases:
  pre_build:
    commands:
      - echo $AWS_REGION
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}
  build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t file_storage .
      - docker tag file_storage:latest ${AWS_ACCOUNT_ID}/file_storage:$IMAGE_TAG # Tag with dynamic tag
      - docker tag file_storage:latest ${AWS_ACCOUNT_ID}/file_storage:latest
      - docker push ${AWS_ACCOUNT_ID}/file_storage:$IMAGE_TAG
      - docker push ${AWS_ACCOUNT_ID}/file_storage:latest
  post_build:
    commands:
      - aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_REGION}
      - kubectl set image deployment/file-storage file-storage=${AWS_ACCOUNT_ID}/file_storage:$IMAGE_TAG
