version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418328607.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t file_storage .
      - docker tag file_storage:latest 905418328607.dkr.ecr.us-east-1.amazonaws.com/file_storage:latest
  post_build:
    commands:
      - docker push 905418328607.dkr.ecr.us-east-1.amazonaws.com/file_storage:latest