image: node:20

pipelines:
  default:
    - step:
        name: Run ESLint
        caches:
          - yarn
        script:
          - yarn install --ignore-engines
          - yarn lint

    - step:
        name: Run Prettier Check
        caches:
          - yarn
        script:
          - yarn install --ignore-engines
          - yarn prettier

    - step:
        name: Run Tests
        services:
          - postgres
        caches:
          - yarn
        script:
          - apt-get update && apt-get install -y libvips-dev
          - echo "APP_ENVIRONMENT=local" > .env
          - echo "DB_PASSWORD=postgres" >> .env
          - echo "DB_USERNAME=postgres" >> .env
          - echo "FS_DRIVER=s3" >> .env
          - yarn install --ignore-engines
          - yarn build
          - yarn test
        environment:
          APP_ENVIRONMENT: local
          APP_VERSION: 0.0.0.1
          DB_PASSWORD: postgres
          DB_USERNAME: postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_DB: 'file_storage'
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        - 5432:5432

caches:
  yarn: ~/.cache/yarn
